version: 1.0.{build}
configuration: Release
before_build:
  - nuget restore
build:
  verbosity: minimal
after_build:
  - cmd: 7z a sql2avro.zip sql2avro\bin\Release\*.*
artifacts:
- path: sql2avro.zip