version: 1.0.{build}
configuration: Release
before_build:
  - nuget restore
build:
  verbosity: minimal
after_build:
  - cmd: cd sql2avro\bin\Release & 7z a sql2avro.zip *.*
artifacts:
- path: sql2avro\bin\Release\sql2avro.zip